version: "3.9"

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    environment:
      MP_UI_BIND_ADDR: "0.0.0.0:8025"
      MP_SMTP_BIND_ADDR: "0.0.0.0:1025"
