/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Account controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AccountStatusDto, AccountEntity } from "../models";

@Injectable({ providedIn: "root" })
export class AccountService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAccountStatus(observe?: 'body', options?: RequestOptions<'json'>): Observable<AccountStatusDto>;
    getAccountStatus(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AccountStatusDto>>;
    getAccountStatus(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AccountStatusDto>>;
    /** Returns payment status for the authenticated user. */
    getAccountStatus(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/account/status`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getAllAccounts(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AccountEntity>>;
    getAllAccounts(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AccountEntity>>>;
    getAllAccounts(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AccountEntity>>>;
    /** Returns a list of all registered users (admin only). */
    getAllAccounts(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/account/list`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getAccountById(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AccountEntity>;
    getAccountById(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AccountEntity>>;
    getAccountById(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AccountEntity>>;
    /** Fetch a single user by their unique ID (admin only). */
    getAccountById(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/account/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateAccountStatus(requestBody: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateAccountStatus(requestBody: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateAccountStatus(requestBody: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Update payment and billing status of a user (admin only). */
    updateAccountStatus(requestBody: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/account/payment`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, requestBody, requestOptions);
    }
}
