/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Persona controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PersonaDto, Persona } from "../models";

@Injectable({ providedIn: "root" })
export class PersonaService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    personaControllerFindAllAdmin(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PersonaDto>>;
    personaControllerFindAllAdmin(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PersonaDto>>>;
    personaControllerFindAllAdmin(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PersonaDto>>>;
    personaControllerFindAllAdmin(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    personaControllerCreate(persona: Persona, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    personaControllerCreate(persona: Persona, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    personaControllerCreate(persona: Persona, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    personaControllerCreate(persona: Persona, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, persona, requestOptions);
    }

    personaControllerUpdate(persona: Persona, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    personaControllerUpdate(persona: Persona, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    personaControllerUpdate(persona: Persona, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    personaControllerUpdate(persona: Persona, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, persona, requestOptions);
    }

    personaControllerFindOne(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PersonaDto>;
    personaControllerFindOne(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PersonaDto>>;
    personaControllerFindOne(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PersonaDto>>;
    personaControllerFindOne(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    personaControllerDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    personaControllerDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    personaControllerDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    personaControllerDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    personaControllerFindAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PersonaDto>>;
    personaControllerFindAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PersonaDto>>>;
    personaControllerFindAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PersonaDto>>>;
    personaControllerFindAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/own`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
