/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Persona controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PersonaDto } from "../models";

@Injectable({ providedIn: "root" })
export class PersonaService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllPersonas(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PersonaDto>>;
    getAllPersonas(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PersonaDto>>>;
    getAllPersonas(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PersonaDto>>>;
    /** Returns all personas with user relation. Requires admin role. */
    getAllPersonas(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createPersona(personaDto: PersonaDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PersonaDto>;
    createPersona(personaDto: PersonaDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PersonaDto>>;
    createPersona(personaDto: PersonaDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PersonaDto>>;
    /** Creates a new persona owned by the authenticated user. */
    createPersona(personaDto: PersonaDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, personaDto, requestOptions);
    }

    updatePersona(personaDto: PersonaDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PersonaDto>;
    updatePersona(personaDto: PersonaDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PersonaDto>>;
    updatePersona(personaDto: PersonaDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PersonaDto>>;
    /** Updates an existing persona belonging to the authenticated user. */
    updatePersona(personaDto: PersonaDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, personaDto, requestOptions);
    }

    getPersona(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PersonaDto>;
    getPersona(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PersonaDto>>;
    getPersona(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PersonaDto>>;
    /** Returns one persona by id if requester is the owner or an admin. */
    getPersona(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deletePersona(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deletePersona(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deletePersona(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Deletes a persona by id if it belongs to the authenticated user. */
    deletePersona(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    getOwnPersonas(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PersonaDto>>;
    getOwnPersonas(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PersonaDto>>>;
    getOwnPersonas(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PersonaDto>>>;
    /** Returns all personas owned by the authenticated user. */
    getOwnPersonas(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/persona/own`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
