/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface Persona {
    /** Unique identifier of the persona */
    id: string;
    /** User that owns this persona */
    user: AccountEntity;
    /** Type of persona */
    type: 'sc' | 'nsc' | 'kid';
    /** First name of the persona */
    firstName: string;
    /** Last name of the persona */
    lastName: string;
    /** Payment status */
    paid: boolean;
    /** Payment timestamp */
    paymentTimestamp: Record<string, unknown>;
}

export interface AccountEntity {
    /** Unique identifier for the account */
    id: string;
    /** Email address of the account */
    email: string;
    /** Role of the account user */
    role: string;
    /** Indicates whether the user has paid */
    payed: boolean;
    /** Optional message associated with the account */
    message?: string;
    /** Indicates whether the user should pay */
    shouldPay: boolean;
    /** List of personas linked to this account */
    personas: Array<Persona>;
    /** Date the account was created */
    createdAt: Date;
    /** Date the account was last updated */
    updatedAt: Date;
}

export interface PersonaDto {
    /** Unique identifier of the persona */
    id: string;
    /** Owner auth ID */
    userId: string;
    /** Type of persona */
    type: 'sc' | 'nsc' | 'kid';
    /** First name */
    firstName: string;
    /** Last name */
    lastName?: string;
    /** Address */
    address?: string;
    /** Mobile number */
    mobileNumber?: string;
    /** Diet */
    diet?: string;
    /** Other diet details */
    dietOther?: string;
    /** Arrival details */
    arrival?: string;
    /** Travelling with a group */
    travellingWithGroup?: boolean;
    /** Group name */
    groupName?: Record<string, unknown>;
    /** Departure details */
    departure?: string;
    /** Support */
    support?: string;
    /** Other support details */
    supportOther?: string;
    /** Accommodation */
    accommodation?: string;
    /** Character name */
    characterName?: string;
    /** Character class */
    characterClass?: string;
    /** Skills */
    skills?: Array<string>;
    /** Is fighter */
    fighter?: boolean;
    /** Important info for GM */
    importantInfoForGM?: string;
    /** Most important aspect */
    mostImportantForCharacter?: string;
    /** Info about friends */
    infoAboutFriends?: string;
    /** Story / lore */
    storyLore?: Record<string, unknown>;
    /** Interests */
    interests?: Array<string>;
    /** Age */
    age?: Record<string, unknown>;
    /** Other */
    other?: Record<string, unknown>;
}

export interface AccountStatusDto {
    payed: boolean;
    shouldPay: boolean;
    message: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
